export const UPDATE_EXERCISES = "UPDATE_EXERCISES";

export const ADD_TO_EXERCISE = "ADD_TO_EXERCISE";
export const REMOVE_FROM_EXERCISE = "REMOVE_FROM_EXERCISE";
export const CLEAR_EXERCISE = "CLEAR_EXERCISE";
export const UPDATE_EXERCISE_DURATION= "UPDATE_EXERCISE_DURATION";
export const UPDATE_EXERCISE_REPETITION = "UPDATE_EXERCISE_REPETITION";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";